### ISSUE TITLE
DiscordWebhook.SendAsync(message) getting SSL Connection Issue

### ISSUE THREAD

**Issue by KRIShark** [N4T4NM/CSharpDiscordWebhook#22]
**By using the dll: CSharpDiscordWebhook.NET.dll

On net6.0 Microsoft.NET.Sdk project on linux (ubuntu:latest).

As I Set the Webhook up:**

`dcWebhook = new DiscordWebhook();
dcWebhook.Uri = new Uri(weebhook_url);`

**and**

**executed this methode: "DiscordWebhook.SendAsync(message);" like:**

`
 DiscordMessage message = new DiscordMessage();
            message.Content = "Mc Server Status is";
            message.TTS = true; //read message to everyone on the channel
            DiscordEmbed embed = new DiscordEmbed();
            embed.Title = "Minecraft Server";
            embed.Description = $"{mcdata.IPAdress.Address.ToString()}:{mcdata.IPAdress.Port.ToString()}";
            embed.Timestamp = mcdata.DateStemp;
            List<EmbedField> fields = new List<EmbedField>();
            
            fields.Add(new EmbedField() { Name = "Version", Value = mcdata.MinecraftServerInfo.MinecraftVersion.ToString(), InLine = false });
            if (mcdata.MinecraftServerInfo.MaxPlayerCount.ToString().Length > 0)
            {
                fields.Add(new EmbedField() { Name = "motd", Value = mcdata.MinecraftServerInfo.ServerMotd, InLine = false });
            }
            fields.Add(new EmbedField() { Name = "Max player", Value = mcdata.MinecraftServerInfo.MaxPlayerCount.ToString(), InLine = false });
            fields.Add(new EmbedField() { Name = "curent Player", Value = mcdata.MinecraftServerInfo.CurrentPlayerCount.ToString(), InLine = false });

            embed.Fields =  fields;
            message.Embeds.Add(embed);
            try
            {
                await dcWebhook.SendAsync(message);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
`

**I get this error message:**

`The SSL connection could not be established, see inner exception.

Unhandled exception. System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.

 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: PartialChain

   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)

   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)

   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)

   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)`

**What dose I wrong?**

**Comment by MrNatanael** [comment]
Check if there is a proxy running
